version: '3'
services:
  rabbit:
    image: 'rabbitmq:management'
    ports:
      - "15672:15672"

  send:
    build:
      context: .
      dockerfile: Dockerfile.send
    volumes:
        - '.:/app'
    restart: always
    depends_on:
      - rabbit
    ports:
      - "3000:3000"

