apiVersion: v1
kind: Pod
metadata:
  name: send-pod
  labels:
    component: send
spec:
  containers:
    - name: send
      image: kashanalikhalid/nodejs-rabbitmq-send
      ports:
        - containerPort: 3000


